# Generated by Django 5.1.6 on 2026-09-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_landlord_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='area',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='parker',
            name='pin',
            field=models.CharField(max_length=128),
        ),
    ]
