"""
Django settings for Parking_tracker project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import shutil
import tempfile
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# Vercel sets VERCEL=1. Its filesystem is read-only apart from /tmp, and instances start fresh often.
ON_VERCEL = bool(os.environ.get('VERCEL'))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '0' if ON_VERCEL else '1') == '1'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured('Set the DJANGO_SECRET_KEY environment variable for production.')
    SECRET_KEY = 'django-insecure-dev-only-=$gpwpaywzwdvz03_mdw1rtclto!f1$e&-ul%7#17lb0z-8!@u'

ALLOWED_HOSTS = [h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,.vercel.app').split(',') if h]
CSRF_TRUSTED_ORIGINS = [o for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', 'https://*.vercel.app').split(',') if o]

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'Authentication',
    'parker_main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Portfolio/demo settings: one-click demo logins, and who built it (shown on the landing page).
DEMO_MODE = os.environ.get('PARKMATCH_DEMO_MODE', '1') == '1'
PROJECT_AUTHOR = os.environ.get('PARKMATCH_AUTHOR', '')
PROJECT_REPO_URL = os.environ.get('PARKMATCH_REPO_URL', '')

# Map tile servers (OpenStreetMap) require a Referer header; Django's default "same-origin" policy strips it.
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

if not DEBUG:
    # Serve collected static files in production; runserver handles them in development.
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'Parking_tracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Authentication.auth.user_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'Parking_tracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Priority: DATABASE_URL (e.g. Postgres on Neon/Vercel, persistent) > the bundled demo database on Vercel > local SQLite.
DEPLOY_DIR = BASE_DIR / 'deploy'


def _writable_copy(src, dest):
    """Vercel can't write inside the bundle, so work from a copy in /tmp (made once per instance)."""
    if src.exists() and not Path(dest).exists():
        if src.is_dir():
            shutil.copytree(src, dest)
        else:
            shutil.copy(src, dest)
    return Path(dest)


if os.environ.get('DATABASE_URL'):
    import dj_database_url
    DATABASES = {'default': dj_database_url.config(conn_max_age=60, ssl_require=not DEBUG)}
elif ON_VERCEL:
    DATABASES = {'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': _writable_copy(DEPLOY_DIR / 'demo.sqlite3', Path(tempfile.gettempdir()) / 'parkmatch.sqlite3'),
    }}
else:
    DATABASES = {'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('PARKMATCH_DB', BASE_DIR / 'db.sqlite3'),
    }}

if ON_VERCEL:
    # Stateless sessions, so a demo login survives requests landing on different instances.
    SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
if ON_VERCEL:
    MEDIA_ROOT = str(_writable_copy(DEPLOY_DIR / 'media', Path(tempfile.gettempdir()) / 'parkmatch-media'))
else:
    MEDIA_ROOT = os.environ.get('PARKMATCH_MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))